restricted/urls.py
# nm.debian.org website restricted pages
#
# Copyright (C) 2012--2013  Enrico Zini <enrico@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import *
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, RedirectView

urlpatterns = patterns('restricted.views',
    url(r'^$', TemplateView.as_view(template_name='restricted/index.html'), name="restricted_index"),
    # AM Personal page
    url(r'^ammain$', 'ammain', name="restricted_ammain"),
    # AM preferences editor
    url(r'^amprofile(?:/(?P<uid>\w+))?$', 'amprofile', name="restricted_amprofile"),
    # Edit personal info
    url(r'^person/(?P<key>[^/]+)$', 'person', name="restricted_person"),
    # Create new process for a person
    url(r'^newprocess_(?P<applying_for>[^/]+)/(?P<key>[^/]+)$', 'newprocess', name="restricted_newprocess"),
    # Show changelogs (minechangelogs)
    url(r'^minechangelogs/(?P<key>[^/]+)?$', 'minechangelogs', name="restricted_minechangelogs"),
    # Impersonate a user
    url(r'^impersonate/(?P<key>[^/]+)?$', 'impersonate', name="impersonate"),
    # Advocate a person to become DD
    url(r'^advocate-dd/(?P<key>[^/]+)$', 'advocate_as_dd', name="advocate_as_dd"),
    # Export database
    url(r'^db-export$', 'db_export', name="restricted_db_export"),
    # Help matching NMs and AMs
    url(r'^nm-am-match/$', 'nm_am_match', name="restricted_nm_am_match"),
    # Advocate a person to become DD
    url(r'^mail-archive/(?P<key>[^/]+)$', 'mail_archive', name="download_mail_archive"),
    url(r'^display-mail-archive/(?P<key>[^/]+)$', 'display_mail_archive', name="display_mail_archive"),
    # Advocate a person to become DD
    url(r'^assign-am/(?P<key>[^/]+)$', 'assign_am', name="assign_am"),
)

urls.py
# NM website
#
# Copyright (C) 2012--2013  Enrico Zini <enrico@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django_dacs.views import login_redirect

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type="text/plain"), name="root_robots_txt"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    url(r'^license/$', TemplateView.as_view(template_name='license.html'), name="root_license"),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html'), name="root_faq"),
    # DACS login
    url(r'^am/login-dacs$', login_redirect, name="login_redirect"),
    url(r'^public/', include("public.urls")),
    url(r'^am/', include("restricted.urls")),
    url(r'^api/', include("api.urls")),
    url(r'^keyring/', include("keyring.urls")),
    url(r'^inconsistencies/', include("inconsistencies.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

restricted/views.py
# nm.debian.org website reports
#
# Copyright (C) 2013  Enrico Zini <enrico@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import http, template, forms
from django.shortcuts import render, render_to_response, redirect
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
import backend.models as bmodels
import minechangelogs.models as mmodels
from backend import const
import backend.auth
import backend.email
import json
import datetime

@backend.auth.is_am
def ammain(request):
    from django.db.models import Min, Max
    ctx = dict()

    ctx["am_available"] = bmodels.AM.list_free()

    if request.am.is_fd or request.am.is_dam:
        DISPATCH = {
            const.PROGRESS_APP_NEW: "prog_app_new",
            const.PROGRESS_APP_RCVD: "prog_app_new",
            const.PROGRESS_ADV_RCVD: "prog_app_new",
            const.PROGRESS_POLL_SENT: "prog_app_new",
            const.PROGRESS_APP_OK: "prog_app_ok",
            const.PROGRESS_AM_RCVD: "prog_am_rcvd",
            const.PROGRESS_AM_OK: "prog_am_ok",
            const.PROGRESS_FD_OK: "prog_fd_ok",
            const.PROGRESS_DAM_OK: "prog_dam_ok",
        }
        for p in bmodels.Process.objects.filter(is_active=True, progress__in=DISPATCH.keys()) \
                        .annotate(
                            started=Min("log__logdate"),
                            last_change=Max("log__logdate")) \
                        .order_by("started"):
            tgt = DISPATCH.get(p.progress, None)
            if tgt is not None:
                p.annotate_with_duration_stats()
                ctx.setdefault(tgt, []).append(p)

        DISPATCH = {
            const.PROGRESS_APP_HOLD: "prog_app_hold",
            const.PROGRESS_FD_HOLD: "prog_app_hold",
            const.PROGRESS_DAM_HOLD: "prog_app_hold",
        }
        for p in bmodels.Process.objects.filter(is_active=True, manager=None, progress__in=DISPATCH.keys()) \
                        .annotate(
                            started=Min("log__logdate"),
                            last_change=Max("log__logdate")) \
                        .order_by("started"):
            tgt = DISPATCH.get(p.progress, None)
            if tgt is not None:
                p.annotate_with_duration_stats()
                ctx.setdefault(tgt, []).append(p)

        DISPATCH = {
            const.PROGRESS_FD_HOLD: "prog_fd_hold",
            const.PROGRESS_DAM_HOLD: "prog_dam_hold",
        }
        for p in bmodels.Process.objects.filter(is_active=True, progress__in=DISPATCH.keys()) \
                        .exclude(manager=None) \
                        .annotate(
                            started=Min("log__logdate"),
                            last_change=Max("log__logdate")) \
                        .order_by("started"):
            tgt = DISPATCH.get(p.progress, None)
            if tgt is not None:
                p.annotate_with_duration_stats()
                ctx.setdefault(tgt, []).append(p)


    DISPATCH = {
        const.PROGRESS_AM_RCVD: "am_prog_rcvd",
        const.PROGRESS_AM: "am_prog_am",
        const.PROGRESS_AM_HOLD: "am_prog_hold",
        const.PROGRESS_AM_OK: "am_prog_done",
        const.PROGRESS_FD_HOLD: "am_prog_done",
        const.PROGRESS_FD_OK: "am_prog_done",
        const.PROGRESS_DAM_HOLD: "am_prog_done",
        const.PROGRESS_DAM_OK: "am_prog_done",
        const.PROGRESS_DONE: "am_prog_done",
        const.PROGRESS_CANCELLED: "am_prog_done",
    }
    for p in bmodels.Process.objects.filter(manager=request.am, progress__in=DISPATCH.keys()) \
                    .annotate(
                        started=Min("log__logdate"),
                        last_change=Max("log__logdate")) \
                    .order_by("started"):
        tgt = DISPATCH.get(p.progress, None)
        if tgt is not None:
            p.annotate_with_duration_stats()
            ctx.setdefault(tgt, []).append(p)

    return render_to_response("restricted/ammain.html", ctx,
                              context_instance=template.RequestContext(request))

def make_am_form(editor):
    excludes = ["person", "is_am_ctte", "created"]

    if editor.is_dam:
        pass
    elif editor.is_fd:
        excludes.append("is_dam")
    else:
        excludes.append("is_fd")
        excludes.append("is_dam")

    class AMForm(forms.ModelForm):
        class Meta:
            model = bmodels.AM
            exclude = excludes
    return AMForm


@backend.auth.is_am
def amprofile(request, uid=None):
    from django.db.models import Min

    if uid is None:
        person = request.person
        am = person.am
    else:
        am = bmodels.AM.lookup_or_404(uid)
        person = am.person

    AMForm = make_am_form(am)

    form = None
    if request.method == 'POST':
        form = AMForm(request.POST, instance=am)
        if form.is_valid():
            cur_am = request.am
            if cur_am == am or cur_am.is_fd or cur_am.is_dam:
                form.save()
            else:
                raise PermissionDenied
            # TODO: message that it has been saved
    else:
        form = AMForm(instance=am)

    processes = bmodels.Process.objects.filter(manager=am).annotate(started=Min("log__logdate")).order_by("-started")

    am_available = bmodels.AM.list_free()

    return render_to_response("restricted/amprofile.html",
                              dict(
                                  person=person,
                                  am=am,
                                  processes=processes,
                                  form=form,
                              ),
                              context_instance=template.RequestContext(request))


@login_required
def person(request, key):
    """
    Edit a person's information
    """
    person = bmodels.Person.lookup_or_404(key)

    # Check permissions
    perms = person.permissions_of(request.person)
    if not perms.can_edit_anything:
        raise PermissionDenied

    # Build the form to edit the person
    excludes = ["user", "created", "status_changed"]
    if not perms.can_edit_bio:
        excludes.append("bio")
    if not perms.can_edit_ldap_fields:
        excludes.extend(("cn", "mn", "sn", "email", "uid", "fpr"))
    if not request.person.is_admin:
        excludes.extend(("status", "fd_comment", "expires", "pending"))

    class PersonForm(forms.ModelForm):
        class Meta:
            model = bmodels.Person
            exclude = excludes

    form = None
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()

            # TODO: message that it has been saved

            # Redirect to the person view
            return redirect(person.get_absolute_url())

    else:
        form = PersonForm(instance=person)

    return render_to_response("restricted/person.html",
                              dict(
                                  person=person,
                                  form=form,
                                  perms=perms,
                              ),
                              context_instance=template.RequestContext(request))

def make_newprocessform(person):
    choices = [(x.tag, x.ldesc) for x in const.ALL_STATUS if x[1] != person.status]

    class NewProcessForm(forms.Form):
        applying_for = forms.ChoiceField(
            required=True,
            label=_("Applying for"),
            choices=choices
        )
        logtext = forms.CharField(
            required=True,
            label=_("Log text"),
            widget=forms.Textarea(attrs=dict(rows=5, cols=80))
        )
    return NewProcessForm

@backend.auth.is_admin
def newprocess(request, applying_for, key):
    """
    Create a new process
    """
    person = bmodels.Person.lookup_or_404(key)

    if applying_for not in person.get_allowed_processes():
        raise PermissionDenied

    process = bmodels.Process(
        person=person,
        progress=const.PROGRESS_APP_NEW,
        is_active=True,
        applying_as=person.status,
        applying_for=applying_for,
    )
    process.save()

    text=""
    if 'impersonate' in request.session:
        text = "[%s as %s]" % (request.user, request.person.lookup_key)
    log = bmodels.Log(
        changed_by=request.person,
        process=process,
        progress=process.progress,
        logtext=text,
    )
    log.save()

    return redirect('public_process', key=process.lookup_key)

def db_export(request):
    # In theory, this isn't needed as it's enforced by DACS
    if request.user.is_anonymous():
        raise PermissionDenied

    if "full" in request.GET:
        if not request.am or not request.am.is_admin:
            raise PermissionDenied
        full = True
    else:
        full = False

    people = list(bmodels.export_db(full))

    class Serializer(json.JSONEncoder):
        def default(self, o):
            if hasattr(o, "strftime"):
                return o.strftime("%Y-%m-%d %H:%M:%S")
            return json.JSONEncoder.default(self, o)

    res = http.HttpResponse(mimetype="application/json")
    if full:
        res["Content-Disposition"] = "attachment; filename=nm-full.json"
    else:

restricted/templates/restricted/advocate-dd.html
{% extends "restricted/base.html" %}
{% load nm %}

{% block head_resources %}
{{block.super}}
<style type="text/css">
    li.warning {
        border: 1pt dashed black;
        background-color: #FDD;
        padding: 2pt;
    }
</style>
{% endblock %}


{% block breadcrumbs %}{{block.super}}
/ <a href="{{ person.get_absolute_url }}">{{person.lookup_key}}</a>
{% endblock %}

{% block content %}

<h1>Advocate {{person.fullname}} to become Debian Developer</h1>

<div id="checklist">
<h2>Important information</h2>
<ul>
    {% if is_early %}
    <li class="warning">
    <b>Warning:</b>
    {% if is_dm %}
    {{person.fullname}} seems to have been a DM for less than 6 months:
    {% else %}
    {{person.fullname}} does not seem to be a DM:
    {% endif %}
    this could be a bit of a rush. The general rule is that
    <a href="http://www.debian.org/devel/join/">Before applying as DD, you
        should have been a DM for about six months</a>. You can still advocate
    {{person.fullname}}, but <em>please provide a good reason</em> of why an account is
    needed so quickly.
    </li>
    {% endif %}
    {% if not process %}
    <li>You are starting a new NM process for {{person.fullname}}. Please only
    do so if you are sure {{person.cn}} wants to apply.</li>
    <li>Also, so you need to specify whether they need upload rights</li>
    {% endif %}
    <li>An email with your advocacy message will be sent to the
        <a href="http://lists.debian.org/debian-newmaint">debian-newmaint</a>
        <em>public</em> mailing list</li>
    <li>See <a href="http://wiki.debian.org/FrontDesk/AdvocacyTips">here</a> for advocacy tips, and
    <a href="https://lists.debian.org/debian-devel-announce/2010/05/msg00003.html">here</a>
    for some more rationale.</li>
    <li>Please be verbose if you can. You may want to write the advocacy in a
    proper text editor and paste it in the form when you are happy with it.</li>
</ul>
</div>

<form action="{% url 'advocate_as_dd' key=person.lookup_key %}" method="post">{% csrf_token %}
<table class="personinfo">
{% if process %}
    {{form.uploading.as_hidden}}
{% else %}
    <tr>
        <th>{{form.uploading.label_tag}}:</th>
        <td>{{form.uploading}} {{form.uploading.errors}}</td>
    </tr>
{% endif %}
    <tr>
        <th>{{form.logtext.label_tag}}:</th>
        <td>{{form.logtext}} {{form.logtext.errors}}</td>
    </tr>
</table>
    <input type="submit" value="Advocate" />
</form>

{% endblock %}

restricted/templates/restricted/amprofile.html
{% extends "restricted/base.html" %}
{% load nm %}

{% block breadcrumbs %}{{block.super}} / <a href="{{person.get_absolute_url}}">{{person.uid}}</a> / <a href="{% url 'restricted_amprofile' uid=person.uid %}">am settings</a>{% endblock %}

{% block content %}

<h1>Debian New Member - Profile</h1>

<table class="personinfo">
    <tr><th>First name</th><td>{{person.cn}}</td></tr>
    <tr><th>Middle name</th><td>{{person.mn|default:""}}</td></tr>
    <tr><th>Last name</th><td>{{person.sn|default:""}}</td></tr>
    <tr><th>Email</th><td>{{person.preferred_email}}</td></tr>
    <tr><th>Account name</th><td>{{person.uid|default:"none chosen yet"}}</td></tr>
    <tr><th>OpenPGP fingerprint</th><td>{{person.fpr}}</td></tr>
    <tr><th>Current status</th><td>{{person.status}}</td></tr>
    {% if can_edit %}
    <tr><th>FD comments</th><td>{{person.fd_comment}}</td></tr>
    {% endif %}
</table>

<h2>Change AM details</h2>

<form action="{% url 'restricted_amprofile' uid=person.uid %}" method="post">{% csrf_token %}
<table class="personinfo">
    {% for field in form %}
    <tr>
        <th>{{field.label_tag}}</th>
        <td>{{field}} {{field.errors}}</td>
    </tr>
    {% endfor %}
</table>
    <input type="submit" value="Change">
</form>

<h2>Applicants</h2>

<table>
{% for p in processes %}
<tr>
    <td>{{p.started.date}}</td>
    <td>{{p.progress|desc_progress}}</td>
    <td><a href="{{ p.get_absolute_url }}">{{p.person}}</a></td>
    <td>{{p.person.fd_comment}}</td>
</tr>
{% endfor %}
</table>

{% endblock %}

restricted/templates/restricted/amstatus.html
{% extends "restricted/base.html" %}
{% load const %}

{% block breadcrumbs %}{{block.super}} / <a href="{% url restricted_amstatus key=process.lookup_key %}">{{process}}</a>{% endblock %}

{% block relatedpages %}
{{block.super}}
<a href="{% url public_nmstatus key=process.lookup_key  %}">public version</a>
{% endblock %}

{% block head %}
{{block.super}}
<script src="{{ MEDIA_URL }}js/jquery-1.7.1.min.js"></script>
<script type="text/javascript">
$(function() {
    var prog = $("#id_progress");
    var text = $("#id_logtext");
    $("#macro_idok").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("ID check passed");
    });
    $("#macro_ppok").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("P&P check passed");
    });
    $("#macro_tsok").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("T&S check passed");
    });
    $("#macro_approve").click(function() {
        prog.val("{{PROGRESS_AM_OK}}");
        text.val("Application approved");
    });
    $("#macro_hold").click(function() {
        prog.val("{{PROGRESS_AM_HOLD}}");
        text.val("Set on hold because of FILLME");
    });
    $("#macro_unhold").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("Back from hold");
    });
});

</script>
{% endblock %}

{% block content %}

<h1><a href="http://qa.debian.org/developer.php?login={{person.email}}">{{person.fullname}}</a></h1>

<h2>Personal information</h2>

<table class="personinfo">
    <tr><th>First name</th><td>{{person.cn}}</td></tr>
    <tr><th>Midtle name</th><td>{{person.mn|default:""}}</td></tr>
    <tr><th>Last name</th><td>{{person.sn|default:""}}</td></tr>
    <tr><th>Email</th><td>{{person.email}}</td></tr>
    <tr><th>Account name</th><td>{{person.uid|default:"none chosen yet"}}</td></tr>
    <tr><th>OpenPGP fingerprint</th><td>{{person.fpr}}</td></tr>
    <tr>
        <th>Advocate{{process.advocates.count|pluralize}}</th>
        <td>
            {% for a in process.advocates.all %}
            {% if a.is_am %}
            <a href="{% url restricted_amprofile uid=a.uid %}">{{a.uid}}</a>{% if not forloop.last %},{% endif %}
            {% else %}
            {{a.uid}}{% if not forloop.last %},{% endif %}
            {% endif %}
            {% endfor %}
        </td>
    </tr>
    <tr><th>Current status</th><td>{{person.status}}</td></tr>
    {% if can_edit %}
    <tr><th>FD comments</th><td>{{person.fd_comment}}</td></tr>
    {% endif %}
</table>
{% if can_edit %}
<a href="{% url restricted_person key=person.lookup_key %}">Edit personal information</a>
{% endif %}

<h2>Progress to become {{ process.applying_for|desc_status }}</h2>

<p>Current progress is: <b>{{ process.progress|desc_progress }}</b>.</p>

{% if can_edit %}
<form action="{% url restricted_amstatus key=process.lookup_key %}" method="post">{% csrf_token %}
    {{ form.as_p }}
<p>
Shortcuts:
{% if process.progress == PROGRESS_AM %}
<button type="button" id="macro_idok">ID check ok</button>
<button type="button" id="macro_ppok">P&amp;P ok</button>
<button type="button" id="macro_tsok">R&amp;S ok</button>
<button type="button" id="macro_approve">Approve applicant</button>
<button type="button" id="macro_hold">On hold</button>
{% endif %}
{% if process.progress == PROGRESS_AM_HOLD %}
<button type="button" id="macro_unhold">Back from hold</button>
{% endif %}
</p>

    <input type="submit" value="Update" />
</form>
{% endif %}

<h2>Progress log</h2>

<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>By</th>
            <th>Progress</th>
            <th>Text</th>
        </tr>
    </thead>
    <tbody>
    {% for l in log %}
    <tr>
        <td>{{l.logdate}}</td>
        <td>
            {% if l.changed_by.is_am %}
            <a href="{% url restricted_amprofile uid=l.changed_by.uid %}">{{l.changed_by.uid}}</a>
            {% else %}
            {{l.changed_by.uid}}
            {% endif %}
        </td>
        <td>{{l.progress|desc_progress}}</td>
        <td>{{l.logtext}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

restricted/templates/restricted/base.html
{% extends "nm-base.html" %}

{% comment %}
Add here bits like breadcrumbs and related pages, that are common to all reports.

Consider different base and private-base templates, with different sets of
breadcrumbs / related pages.

{% block navbar %}
{{block.super}}
<li><a href="{% url 'restricted_nmelist' %}">List of applicants</a></li>
{% endblock %}

{% endcomment %}


{% comment %}
TODO: use a specific bit for logged in information and logout buttons; needs
      more blocks in the base debian template, though
{% block relatedpages %}{{block.super}} <a href="{% url 'restricted_index' %}">{{user}}</a>{% endblock %}
{% endcomment %}

{% block content %}
<h1>Debtags Report Template</h1>
{% endblock %}

restricted/templates/restricted/index.html
{% extends "restricted/base.html" %}

{% block content %}

<h1>Debian New Member - AM area</h2>

<p>There is going to be some sort of introduction here</p>

{% endblock %}

restricted/templates/restricted/nmstatus.html
{% extends "restricted/base.html" %}
{% load nm %}
{% load js %}

{% block breadcrumbs %}{{block.super}} / <a href="{{person.get_absolute_url}}">{{person.lookup_key}}</a> / <a href="{% url restricted_nmstatus key=process.lookup_key %}">progress</a>{% endblock %}

{% block relatedpages %}
{{block.super}}
<a href="{{person.get_ddpo_url}}">DDPO</a>
<a href="{{person.get_ddportfolio_url}}">DDPortfolio</a>
{% if request.person.is_admin %}
<a href="{% url admin:backend_process_change process.id %}">admin</a>
{% endif %}
{% endblock %}

{% block head_resources %}
{{block.super}}
{% jsinclude "core" %}
{% endblock %}


{% block head %}
{{block.super}}
<script type="text/javascript">
$(function() {
    var prog = $("#id_progress");
    var text = $("#id_logtext");
    $("#macro_idok").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("ID check passed");
    });
    $("#macro_ppok").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("P&P check passed");
    });
    $("#macro_tsok").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("T&S check passed");
    });
    $("#macro_approve").click(function() {
        prog.val("{{PROGRESS_AM_OK}}");
        text.val("Application approved");
    });
    $("#macro_hold").click(function() {
        prog.val("{{PROGRESS_AM_HOLD}}");
        text.val("Set on hold because of FILLME");
    });
    $("#macro_unhold").click(function() {
        prog.val("{{PROGRESS_AM}}");
        text.val("Back from hold");
    });
});

</script>
{% endblock %}

{% block content %}

<h1>{{person.fullname}}</h1>

<h2>Personal information</h2>

<table class="personinfo">
    <tr><th>Applicant</th><td><a href="{{person.get_absolute_url}}">{{person.fullname}} &lt;{{person.email}}&gt;</a></td></tr>
    <tr><th>Account name</th><td>{{person.uid|default:"none chosen yet"}}</td></tr>
    <tr><th>OpenPGP fingerprint</th><td>{{person.fpr}}</td></tr>
    {% if process.manager %}
    <tr><th>Manager</th><td><a href="{{process.manager.get_absolute_url}}">{{process.manager.person.uid}}</a></td></tr>
    {% endif %}
    <tr>
        <th>Advocate{{process.advocates.count|pluralize}}</th>
        <td>
            {% for a in process.advocates.all %}
            <a href="{{ a.get_absolute_url }}">{{a.uid}}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        </td>
    </tr>
    <tr><th>Process</th><td>{{person.status|desc_status}} → {{process.applying_for|desc_status}}</td></tr>
    {% if can_edit %}
    <tr><th>FD comments</th><td>{{person.fd_comment}}</td></tr>
    {% endif %}
</table>
{% if can_edit %}
<a href="{% url restricted_person key=person.lookup_key %}">Edit personal information</a>
{% endif %}

<h2>Progress to become {{ process.applying_for|desc_status }}</h2>

<p>Current progress is: <b>{{ process.progress|desc_progress }}</b>.</p>

{% if can_edit %}
<form action="{% url restricted_nmstatus key=process.lookup_key %}" method="post">{% csrf_token %}
    {{ form.as_p }}
<p>
Shortcuts:
{% if process.progress == PROGRESS_AM %}
<button type="button" id="macro_idok">ID check ok</button>
<button type="button" id="macro_ppok">P&amp;P ok</button>
<button type="button" id="macro_tsok">T&amp;S ok</button>
<button type="button" id="macro_approve">Approve applicant</button>
<button type="button" id="macro_hold">On hold</button>
{% endif %}
{% if process.progress == PROGRESS_AM_HOLD %}
<button type="button" id="macro_unhold">Back from hold</button>
{% endif %}
</p>

    <input type="submit" value="Update" />
</form>
{% endif %}

<h2>Progress log</h2>

<table>
    <thead>
        <tr>
            {% if am.is_fd %}
            <th>Actions</th>
            {% endif %}
            <th>Date</th>
            <th>By</th>
            <th>Progress</th>
            <th>Text</th>
        </tr>
    </thead>
    <tbody>
    {% for l in log %}
    <tr>
        {% if am.is_fd %}
        <td><a href="{% url admin:backend_log_change l.id %}">edit</a></td>
        {% endif %}
        <td>{{l.logdate|date:"Y-m-d"}}</td>
        <td>
            <a href="{{l.changed_by.get_absolute_url}}">{{l.changed_by.uid}}</a>
        </td>
        <td>{{l.progress|desc_progress}}</td>
        <td>{{l.logtext}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}